name: Generate SBOM from Built Source (Syft)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      - name: Build project (no APK)
        run: ./gradlew build --no-daemon

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM from build directory
        run: |
          mkdir -p sbom
          syft dir:./ --exclude ./buildSrc -o spdx-json > sbom/nowinandroid.spdx.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: nowinandroid-sbom
          path: sbom/
